# Generated by Django 2.1.4 on 2019-01-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBAccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaisinfo',
            name='RelaisEnabled',
            field=models.BooleanField(default=True, verbose_name='Aktiviert'),
        ),
    ]
