# Generated by Django 2.1.4 on 2019-01-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBAccess', '0002_relaisinfo_relaisenabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relaisinfo',
            old_name='RelaisEnabled',
            new_name='RelaisState',
        ),
    ]
