# Generated by Django 2.1.4 on 2019-01-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBAccess', '0003_auto_20190127_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrelaisinfo',
            name='ProjectID',
        ),
        migrations.RemoveField(
            model_name='projectrelaisinfo',
            name='RelaisID',
        ),
        migrations.AddField(
            model_name='projectrelaisinfo',
            name='Project',
            field=models.ForeignKey(db_column='ProjectID', default='', on_delete=django.db.models.deletion.CASCADE, to='DBAccess.ProjectInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrelaisinfo',
            name='Relais',
            field=models.ForeignKey(db_column='RelaisID', default='', on_delete=django.db.models.deletion.CASCADE, to='DBAccess.RelaisInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorinfo',
            name='SensorUnit',
            field=models.CharField(default='', max_length=20, verbose_name='Einheit z.B. C°'),
        ),
        migrations.AlterField(
            model_name='scheduledtaskinfo',
            name='ObjectType',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('file', 'File'), ('relais', 'relais')], default='file', max_length=30, verbose_name='Objekttyp'),
        ),
    ]
