# Generated by Django 2.1.4 on 2019-01-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBAccess', '0004_auto_20190127_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorinfo',
            name='SensorCustomData',
            field=models.TextField(default='', verbose_name='CustomData'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorinfo',
            name='SensorUnit',
            field=models.CharField(default='', max_length=20, verbose_name='Einheit z.B. °C'),
        ),
    ]
