# Generated by Django 2.1.4 on 2019-01-30 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBAccess', '0005_auto_20190127_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventloginfo',
            name='UserID',
        ),
        migrations.AddField(
            model_name='eventloginfo',
            name='UserInfo',
            field=models.ForeignKey(db_column='UserID', default=1, on_delete=models.SET(-1), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
